name: Build WebForms App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Restore NuGet packages
      run: nuget restore TP_Grupo_12.sln

    - name: Build solution
      run: msbuild TP_Grupo_12.sln /p:Configuration=Release
